
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  producer:
    build: ./producer
    depends_on:
      - kafka
    restart: always
    networks:
      - kafka-net

  worker1:
    build: ./worker1
    depends_on:
      - kafka
    restart: always
    environment:
      GROUP_ID: worker-group
    networks:
      - kafka-net

  worker2:
    build: ./worker2
    depends_on:
      - kafka
    restart: always
    environment:
      GROUP_ID: worker-group
    networks:
      - kafka-net

  backend:
    build: ./backend
    depends_on:
      - kafka
    restart: always
    ports:
      - "5000:5000"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
